name: CI
on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 */2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Upload new cases data
      uses: wei/curl@master
      with:
        args: -X POST 'https://api.tinybird.co/v0/datasources?url=https://raw.githubusercontent.com/datadista/datasets/master/COVID%2019/ccaa_covid19_casos_long.csv&mode=replace&name=ccaa_covid19_casos_long&token=${{ secrets.TOKEN }}'
