name: CI
on:
  push:
    branches:
      - master
  schedule:
    - cron:  '*/2 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      env:
        TOKEN: ${{ secrets.TOKEN }}

    - name: Update cases Data Source
      run: curl -H "Authorization: Bearer $TOKEN" -X POST "https://api.tinybird.co/v0/datasources?url=https://raw.githubusercontent.com/datadista/datasets/master/COVID%2019/ccaa_covid19_casos_long.csv&mode=replace&name=ccaa_covid19_casos_long"
